language: python

dist: bionic
sudo: false

addons:
  apt:
    packages:
      - pandoc

env:
  global:
    - secure: ""

git:
  depth: 1000

matrix:
  fast_finish: true
  include:
  - python: 3.7

before_install:
  - pip install pip --upgrade
  - pip install -r requirements.txt -q
  - pip install -r requirements-dev.txt -q

install:
  - pip install -e .

script:
  - cd docs
  - pip install -r requirements.txt -q
  - jupyter kernelspec list
  - make html

after_success:
  - cd ..
  - set -e
  - pip install doctr
  - doctr deploy --build-tags --built-docs docs/_build/html/ devel
  - |
    if [[ -z ${TRAVIS_TAG} ]]; then
      echo "Not a tagged build."
    else
      doctr deploy --build-tags --built-docs docs/_build/html/ .
    fi
